urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

# uncomment maintenance.html line to close the tool

from django.conf.urls import patterns, url, include

# from django.views.generic import list_detail

from django.conf import settings
from django.contrib import admin
from django.conf.urls import patterns, url, include
admin.autodiscover()

from paraminfo.models import *
from ui.views import main_site
# from django.views.generic.simple import direct_to_template
from django.views.generic import TemplateView

# -------- OPUS Apps -------------------------------------

# results - getting data

base_urlpatterns = patterns( 'results.views',
    (r'^api/data.(json|zip|html|csv)$', 'getData'),
    (r'^api/images/(thumb|small|med|full).(json|zip|html|csv)$','getImages'),
    (r'^api/image/(?P<size>[thumb|small|med|full]+)/(?P<ring_obs_id>[0-9a-zA-Z\-_]+).(?P<fmt>[json|zip|html|csv]+)$', 'getImage'),
    (r'^api/files/(?P<ring_obs_id>[0-9a-zA-Z\-_]+).(?P<fmt>[json|zip|html|csv]+)$','getFilesAPI'),
    (r'^api/files.(?P<fmt>[json|zip|html|csv]+)$', 'getFilesAPI'),
    (r'^api/metadata/(?P<ring_obs_id>[0-9a-zA-Z\-_]+).(?P<fmt>[json|html]+)$','get_metadata'),
    (r'^collections/data.csv$','get_csv'),
)


# metadata - getting information about a data
base_urlpatterns += patterns('metadata.views',
    (r'^api/meta/result_count.(?P<fmt>[json|zip|html|csv]+)$', 'getResultCount'),
    (r'^api/meta/mults/(?P<slug>[-\sa-zA-Z]+).(?P<fmt>[json|zip|html|csv]+)$', 'getValidMults'),
    (r'^api/meta/range/endpoints/(?P<slug>[-\sa-zA-Z0-9]+).(?P<fmt>[json|zip|html|csv]+)$', 'getRangeEndpoints'),
    (r'^api/fields/(?P<field>\w+).(?P<fmt>[json|zip|html|csv]+)$','getFields'),
    (r'^api/fields.(?P<fmt>[json|zip|html|csv]+)$', 'getFields'),
    # (r'^api/category/(?P<category>\w+).(?P<fmt>[json|zip|html|csv]+)$','getCats'),
    # (r'^api/categories.(?P<fmt>[json|zip|html|csv]+)$', 'getCats'),
    # (r'^api/meta/histogram/(?P<fmt>[labels|ids]+)/.(?P<fmt>[json|zip|html|csv]+)$', 'getValidMults'),   # returns mult values+counts
)


# making downloads
base_urlpatterns += patterns('downloads.views',
    (r'^zip/(?P<ring_obs_id>[0-9a-zA-Z\-_]+).(?P<fmt>[json]+)$', 'create_download'),
    (r'^collections/download/(?P<collection_name>[default]+).zip$', 'create_download'),
    (r'^collections/download/info/$','get_download_info_API'))


# UI resources - the homepage
base_urlpatterns += patterns('ui.views',
    # url(r'^$', TemplateView.as_view(template_name='maintenance.html'), name="home"),
    (r'^$', main_site.as_view()),
    (r'^opus/$', main_site.as_view()),
    (r'^about/$', 'about'),
    (r'^table_headers.html$', 'get_table_headers'),
    (r'^browse_headers.html$', 'get_browse_headers'),
    (r'^menu.html$', 'getMenu'),
    (r'^quick.html$', 'getQuickPage'),
    (r'^forms/widget/(?P<slug>[-\sa-zA-Z0-9]+).(?P<fmt>[json|zip|html|csv]+)$', 'getWidget'),
    (r'^forms/column_chooser.html$', 'getColumnChooser'),
    (r'^api/detail/(?P<ring_obs_id>[0-9a-zA-Z\-_]+).(?P<fmt>[json|zip|html]+)$', 'init_detail_page'),
)


# guide - app runs guide to  api
base_urlpatterns += patterns('guide.views',
    (r'^api/$', 'guide'),
    (r'^developer/$', 'guide'),  # api help pages
    (r'^api/guide.html$', 'guide'))  # api help pages


# user_collections - all your carts are belong to us
base_urlpatterns += patterns('user_collections.views',
    (r'^collections/(?P<collection_name>[default]+)/(?P<action>[add|remove|addrange|removerange]+).json$', 'edit_collection'),
    (r'^collections/(?P<collection_name>[default]+)/view.html$','view_collection'),
    (r'^collections/(?P<collection_name>[default]+)/status.json$','collection_status'),
    (r'^collections/reset.html$', 'reset_sess'),
    (r'^collections/(?P<collection_name>[default]+)/(?P<action>[addrange|removerange]+)/test.html$', 'edit_collection_range'),
)


# mobile - mobile volumes browser
base_urlpatterns += patterns('mobile.views',
    (r'^mobile.html$', 'menus'),
    (r'^mobile/gallery/(?P<volume_id>\w+)/(?P<page>\w+).json$', 'gallery'),
    (r'^mobile/image/(?P<ring_obs_id>[0-9a-zA-Z\-_]+).html$', 'image'),
    (r'^mobile/detail/(?P<ring_obs_id>[0-9a-zA-Z\-_]+).html$', 'detail'))  # api help pages


# django admin
base_urlpatterns += patterns('', (r'^admin/doc/',
                        include('django.contrib.admindocs.urls')),
                        (r'^admin/', include(admin.site.urls)))

if settings.DEBUG:
    base_urlpatterns += patterns('django.views.static',
                            (r'^static_media/(?P<path>.*)$', 'serve', {'document_root': '/Users/lballard/projects/opus/static_media/', 'show_indexes': True}))






from django.http import HttpResponse


urlpatterns = patterns('',
    ('^', include(base_urlpatterns)), # iff you wish to maintain the un-prefixed URL's too
    ('^%s/' % settings.BASE_PATH,  include(base_urlpatterns)),
)

#########################################
"""
# session test

from django import http

def session_test_1(request):
    request.session['test'] = 'Session Vars Worked!'
    return http.HttpResponseRedirect('done/?session=%s' % request.session.session_key)

def session_test_2(request):
    return http.HttpResponse('<br>'.join([
        request.session.session_key,
        request.GET.get('session'),
        request.session.get('test', 'Session is Borked :(')
         ]))

urlpatterns += patterns('',
        (r'^session-test/$', session_test_1),
        (r'^session-test/done/$', session_test_2),
)
"""

apps/guide/models.py
from django.db import models



# Create your models here.
class Resource(models.Model): 
    name = models.CharField(max_length=70)
    desc = models.CharField(max_length=255)    
    display = models.BooleanField(default=True)
    disp_order = models.IntegerField(blank=True, null=True)
    group = models.ForeignKey("Group")
    
    class Meta:
        ordering = ['disp_order']

    def __unicode__(self):
        return u"%s" % self.name                               

    def save(self, *args, **kwargs):
        model = self.__class__
        # model.objects.update(group)

        if self.disp_order is None:
            # Append
            try:
                last = model.objects.order_by('-disp_order')[0]
                self.disp_order = last.disp_order + 1
            except IndexError:
                # First row
                self.disp_order = 0

        return super(Resource, self).save(*args, **kwargs)

    

class Group(models.Model):
    name = models.CharField(max_length=150, blank=True)
    desc = models.TextField(blank=True, null=True)  
    disp_order = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ['disp_order']

    def __unicode__(self):
        return self.name
      
        
    
class KeyValue(models.Model): 
    key = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    disp_order = models.IntegerField(blank=True, null=True)
    display = models.BooleanField(default=True)
    resource = models.ForeignKey("Resource")       
    
    class Meta:
        ordering = ['disp_order']

    def __unicode__(self):
        return u"%s" % self.key
        
class Example(models.Model): 
    intro = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    display = models.BooleanField(default=True)
    disp_order = models.IntegerField(blank=True, null=True)
    resource = models.ForeignKey("Resource")
                                        
    class Meta:
        ordering = ['disp_order']

    def __unicode__(self):
        return u"%s" % self.intro

apps/guide/views.py
from guide.models import *
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponse,Http404
from metrics.views import update_metrics

def guide(request):
    update_metrics(request)

    base_url = 'http://' +request.META['HTTP_HOST'] + '/opus/'
    groups = Group.objects.all()
    resources = Resource.objects.filter(display=True).select_related().order_by('disp_order')

    return render_to_response('guide.html',locals(), context_instance=RequestContext(request))


# def update(request)

apps/guide/templates/guide.html
{% extends "base.html" %}

{% block content %}

<div class = "container">

	<div class = "col-md-8">
		{% block more_head %}
		<link rel="stylesheet" href="{{ MEDIA_URL }}styles/api_guide.css" type="text/css" media="screen">
		{% endblock %}


		<h1>OPUS API Guide</h1>

		<div>
			<p>
				This guide describes the API that drives <a href = "http://pds-rings-tools.seti.org/opus">OPUS, an outer planets data search tool</a> produced by the <a href = "http://pds-rings.seti.org">NASA PDS Rings Node</a>. Any search that can be performed in OPUS can also be requested as an API call. Below are several examples. Please <a href = "http://pds-rings.seti.org/cgi-bin/comment-form.pl"> send us questions or comments</a>.
			</p>
		</div>

		<div class = "jumpto">
		{% for group in groups %}
		<a href = "#{{ group.name|slugify }}">{{ group.name }}</a> <br>
		{% endfor %}
		</div>

		{% for group in groups %}
			<div class = "section">
			<a name = "{{ group.name|slugify }}"></a>

			<h2>{{ group.name }}</h2>
			<p>{{ group.desc }}</p>

			{% for resource in group.resource_set.all %}

		  		<div class = "intro">
					<h3>{{ resource.name }}</h3>

					<p>{{ resource.desc }}</p>
				</div>

			   <ul class = "keyvals">

					{% for keyval in resource.keyvalue_set.all %}
						 <li><strong>{{keyval.key}}: </strong> {{keyval.value}} </li>

				    {% endfor %}
				</ul>

				<div class = "examples">
					<strong> Example: </strong>

					<ul>
					{% for example in resource.example_set.all %}

		  		  		<li><p id = "example_intro">{{ example.intro }}  </p>

				    	<p><a href = "{{ base_url }}{{ example.link }}" target = "_blank">
							{{ base_url }}{{ example.link }}
						</a></p>

						<p class = "cutpaste">
							<!-- curl -O {{ base_url }}{{ example.link }} -->
							<input type = "text" value = "wget {{ base_url }}{{ example.link }}">
						</p>

						</li>

					{% endfor %}

					</ul>
			   </div>
			</ul>
			{% endfor %}

		<a href = "#">back to top</a>
		</div> <!-- groups -->
		{% endfor %}

	</div>

{% endblock %}